# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agiler < Formula
  desc "Command-line interface for Agiler."
  homepage "https://agiler.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agilercloud/cli/releases/download/v0.1.0/agiler_0.1.0_darwin_x86_64.tar.gz"
      sha256 "4f75521a57342baf5d4dac454e458c1dc99d17dda4c9641ce3e188f91bef1756"

      define_method(:install) do
        bin.install "agiler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agilercloud/cli/releases/download/v0.1.0/agiler_0.1.0_darwin_arm64.tar.gz"
      sha256 "b16ff7cd25433b12b4e4af0351df482f80713b8789759bc2aafb2be0729ed685"

      define_method(:install) do
        bin.install "agiler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agilercloud/cli/releases/download/v0.1.0/agiler_0.1.0_linux_x86_64.tar.gz"
      sha256 "c3e98ab235381238a520ca0d518f040708b71c3a11d02b4f2bae2a4b55a47bc0"
      define_method(:install) do
        bin.install "agiler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agilercloud/cli/releases/download/v0.1.0/agiler_0.1.0_linux_arm64.tar.gz"
      sha256 "52a139fcbcb22be32cac462d9523ba853f2fb4ccffa49563bccd19442cec0cb7"
      define_method(:install) do
        bin.install "agiler"
      end
    end
  end

  test do
    system "#{bin}/agiler version"
  end
end
