# This file was generated by GoReleaser. DO NOT EDIT.
cask "agiler" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "8a66e06e83b6e70a4613b1bd906bc6fe4f2f48e4cf6a1df99e4be5501d0298ed"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "872db5efd6752d3f9d7f7ba8a3204eec4d03930b7f62e7e2e601edeeaae771da"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "940728f7f0c271d5bfd7bea888a8af6afa1fb717ea33bfc4fed248cbba5d0ab6"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ffb9489cd11f5a5183541361abdc543608e1f338105775e4436cca7543d59ed"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "agiler"
  desc "Command-line interface for Agiler."
  homepage "https://agiler.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agiler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agiler"]
    end
  end

  # No zap stanza required
end
