# This file was generated by GoReleaser. DO NOT EDIT.
cask "agiler" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "7511df138f3af94aaeca7ae425f1fb1b7402c3195f27665324000269ccea1062"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a69a180714b57625321bf933443535862ef9a75a9afbb45881508dffcf0d8c1"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5aa59e3a3cad8aacb90a71741fdd51ef676de54ae21564abda2256bc2e5a53d1"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f468fac17797a856e356acacd97d6af0eea30db6719520dfac5f6f17008aac36"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "agiler"
  desc "Command-line interface for Agiler."
  homepage "https://agiler.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agiler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agiler"]
    end
  end

  # No zap stanza required
end
