# This file was generated by GoReleaser. DO NOT EDIT.
cask "agiler" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "b6de2f2f010916904cb30b6ae1eef83cfd839658c1211fb281b370ad5cb80ba9"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "031c455f83992b340e3b71471d64303d8200d83736719350e9c4bf78bdb76c85"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "beb18cdf48da5ff8a558098c24281b791a7dc175d47560ed1c981ec5e47ca148"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7b6f529086abc6cfde2c56232ca8948afa71d49e829b5166482c2cb9b1cd96a8"
      url "https://github.com/agilercloud/cli/releases/download/v#{version}/agiler_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agiler"
  desc "Command-line interface for Agiler."
  homepage "https://agiler.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agiler"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agiler"]
    end
  end

  # No zap stanza required

end
